parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: kaiako
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b232aa7cf763adbd4c59b61d6017f4b48e3b487e
    database_path: null
