security:
    firewalls:
      # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login: 
                login_path: user_login
                check_path: user_login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: user_logout
            remember_me:
                key: kaiako1234
                lifetime: 3600
    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register_teacher, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register_student, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/account_teacher, roles: [ROLE_USER_TEACHER] }
        - { path: ^/user/account_student, roles: [ROLE_USER_STUDENT] }
        - { path: ^/user/*, roles: [ROLE_USER_TEACHER, ROLE_USER_STUDENT] }
        - { path: ^/backend/*, roles: ROLE_ADMIN }
    providers:
        chain_provider:
            chain:
                providers: [user_students, user_teachers]
        user_students:
            entity: { class: kaiako\UserBundle\Entity\Student, property: id }
        user_teachers:
            entity: { class: kaiako\UserBundle\Entity\Teacher, property: id }
        # Usuarios del backend
        administradores:
            memory:
                users:
                    # user = admin, pass = 1234
                    admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER_TEACHER, ROLE_USER_STUDENT, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        kaiako\UserBundle\Entity\Student: sha512
        kaiako\UserBundle\Entity\Teacher: sha512
        Symfony\Component\Security\Core\User\User: sha512