user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UserBundle:Default:index }
    
user_teacher_register:
    pattern: /register_teacher/{errorMsg}
    defaults: { _controller: UserBundle:Default:registerTeacher }
