user_homepage:
    pattern:  /panel/{name}
    defaults: { _controller: UserBundle:Default:index }
    
user_login:
    pattern: /login
    defaults: { _controller: UserBundle:Default:login }
    
user_login_check:
    pattern: /login_check
    
user_logout:
    pattern: /logout
    
user_register:
    pattern: /register
    defaults: { _controller: UserBundle:Default:register }
    
user_teacher_register:
    pattern: /register_teacher/{errorMsg}
    defaults: { _controller: UserBundle:Default:registerTeacher }
    
user_student_register:
    pattern: /register_student/{errorMsg}
    defaults: { _controller: UserBundle:Default:registerStudent }
